### ISSUE TITLE
[UI-FIX] Settings is truncated on smaller devices

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#85]
**Section or interface element**
Hamburger menu should be scrollable if not scaled to fit smaller devices

**Reason**
It's currently possible to view the whole of the options in the hamburger [menu](url
![Screenshot_20200910-121446](https://user-images.githubusercontent.com/2853264/92724358-60869a00-f362-11ea-9dc0-6a19d809f2bd.png)
)

**Description**
A clear and concise description of how the look and feel should be.

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
can you be more explicit? what is smaller devices here? I mean... which device is this one? and Iphone 4, Jio phone, galaxy pocket? or is it a regular screen 5' size phone? are you able to tap the settings? are you able to scroll? If not this won't be a mere aesthetics adjustment it would be a bug.

**Comment by ibanezvaio** [comment]
Samsung S6 - 5.1 inch screen size. I can tap Settings but the ui does not scroll

**Comment by t3nshi** [comment]
I already figure it out. Fix available on next version

**Comment by t3nshi** [comment]
I already tested on very small screens and even then the menu is scrollable to reveal any of the items.

**Comment by ibanezvaio** [comment]
Still not scrollable for me in 0.5.4. Maybe it's specific to this device

**Comment by ibanezvaio** [comment]
Confirmed fixed in 0.5.4(1), although [Set Limits] is now missing from the hamburger menu
